### ISSUE TITLE
Uncaught ReferenceError: webpackJsonp is not defined / ES6 dynamic import, code split

### ISSUE THREAD

**Issue by aheissenberger** [geelen/react-snapshot#77] opened 2017-10-17 15:11 UTC
Simple create-react-app with react-router, react-loadable and 
dynamic import based on **react-snapshot@next**:
https://github.com/aheissenberger/react-snapshot_issue_dynamic-import

Loading one of the static generated html files `react-scripts build && react-snapshot` - e.g. `http://127.0.0.1:8001/about.html` will show the rendered content and then after loading XXXX.chunk.js throwing the following error msg:
```
1.4ee8bb8e.chunk.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at 1.4ee8bb8e.chunk.js:1
```
the whole `<switch>` block will be unmounted from the react tree

**Comment by stereobooster** [comment] 2017-10-23 19:52
duplicate of https://github.com/geelen/react-snapshot/issues/66

**Closed** 2017-11-02 01:39 UTC
