### ISSUE TITLE
Different 'build' path

### ISSUE THREAD

**Issue by georgest** [geelen/react-snapshot#78] opened 2017-10-17 15:26 UTC
What happens when you have different `build` path.
For example my build folder is in `./web/build`.

When I run react-snapshot it doesn't not render anything. The console output is:
`🕷   Starting crawling http://localhost:59703/`
`🔥 'render' from react-snapshot was never called. Did you replace the call to ReactDOM.render()?`
`🕸   Finished crawling.`

**Comment by stereobooster** [comment] 2017-10-23 19:53
duplicate of https://github.com/geelen/react-snapshot/issues/42

**Closed** 2017-11-02 01:11 UTC
