### ISSUE TITLE
Error: Not implemented: window.scrollTo, 

### ISSUE THREAD

**Issue by kuongknight** [geelen/react-snapshot#93] opened 2018-01-05 04:57 UTC
I found error "Error: Not implemented: window.scrollTo", I fixed it by custom react-snapshot
Then it is working, but react-snapshot render same with all page (without react render, only html with script tags)

**Comment by stereobooster** [comment] 2018-01-05 08:48
Can you provide more clear description of the issue and reproducible example?

**Comment by kuongknight** [comment] 2018-01-05 10:03
Try add `componentWillMount() {
    window.scrollTo(0, 0)
  }` to App.js and build

**Comment by stereobooster** [comment] 2018-01-05 10:32
If you are reporting about not implemented `scrollTo`. Yes this is known issue, because `react-snapshot` using `jsdom` which implements only subset of browser APIs. You can file an issue against `jsdom` as well. 

From readme:
> Is JSDOM gonna hold us back at some point?

Related https://github.com/geelen/react-snapshot/issues/40

**Comment by kuongknight** [comment] 2018-01-05 10:37
We should make possible config `beforeParse` for jsdom.

**Comment by stereobooster** [comment] 2018-01-13 13:34
Jsdom issue won't be fixed, see https://github.com/geelen/react-snapshot/pull/44#issuecomment-341292537. If this answers your question please close issue. Thanks

**Closed** 2018-01-16 15:29 UTC
